name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
    - name: Setup Windows PATH
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build zlib
      if: matrix.os == 'windows-latest'
      working-directory: lib/zlib-ng
      run:
        cmake .
        cmake --build .
    - name: Run tests
      run: cargo test --all-features
